# Generated by Django 3.0.7 on 2020-09-26 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NGO_App', '0002_ngoprofile_verfied'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgoRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=60)),
                ('quantity', models.IntegerField()),
                ('message', models.CharField(max_length=300)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NGO_App.NGOProfile')),
            ],
        ),
    ]
