# Generated by Django 3.0.7 on 2020-09-26 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NGO_App', '0003_ngorequirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_add_requirement', models.CharField(max_length=50)),
                ('donated_items', models.IntegerField()),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NGO_App.NGOProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NGO_App.UserProfile')),
            ],
        ),
    ]
