# Generated by Django 3.0.7 on 2020-09-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO_App', '0006_auto_20200927_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngoprofile',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
