# Generated by Django 3.0.7 on 2020-09-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NGO_App', '0007_auto_20200927_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngoprofile',
            name='description',
        ),
    ]
